### ISSUE TITLE
Let's Encrypt example

### ISSUE THREAD

**Issue by mrbluecoat** [joaopandolfi/PoW-Shield-Go#2]
Cool project! Any guidance on leveraging Let's Encrypt for TLS?

https://github.com/joaopandolfi/PoW-Shield-Go/blob/main/.env.example#L50

**Comment by joaopandolfi** [comment]
Yes!

You just need setup the path of priv key and certificate generated by `certbot` (for example)

In the most scenarios, the default path is:
- certificate  `/etc/letsencrypt/live/example.domain.com/fullchain.pem` 
- privkey `/etc/letsencrypt/live/example.domain.com/privkey.pem`

And don-t forget to put setup `USE_TLS` to `true`
